Repository sqlc-dev/sqlc, pull requests merged in 2023-06, with the labels that each got.

#1986 sqlite: fixed sqlite column type override
  internal/cmd/shim.go
  internal/codegen/sdk/sdk.go
  internal/endtoend/testdata/overrides/sqlite/go/db.go
  internal/endtoend/testdata/overrides/sqlite/go/models.go
  internal/endtoend/testdata/overrides/sqlite/query.sql
  internal/endtoend/testdata/overrides/sqlite/schema.sql
  internal/endtoend/testdata/overrides/sqlite/sqlc.json
  internal/endtoend/testdata/overrides_go_struct_tags/sqlite/go/db.go
  internal/endtoend/testdata/overrides_go_struct_tags/sqlite/go/models.go
  internal/endtoend/testdata/overrides_go_struct_tags/sqlite/query.sql
  internal/endtoend/testdata/overrides_go_struct_tags/sqlite/schema.sql
  internal/endtoend/testdata/overrides_go_struct_tags/sqlite/sqlc.json
  internal/endtoend/testdata/overrides_go_types/sqlite/go/db.go
  internal/endtoend/testdata/overrides_go_types/sqlite/go/models.go
  internal/endtoend/testdata/overrides_go_types/sqlite/query.sql
  internal/endtoend/testdata/overrides_go_types/sqlite/schema.sql
  internal/endtoend/testdata/overrides_go_types/sqlite/sqlc.json
Labels: :books: sqlite

#1746 feat(mysql): handle unsigned integers
  examples/ondeck/mysql/db_test.go
  examples/ondeck/mysql/models.go
  internal/cmd/shim.go
  internal/codegen/golang/go_type.go
  internal/codegen/golang/mysql_type.go
  internal/compiler/output_columns.go
  internal/compiler/query.go
  internal/compiler/query_catalog.go
  internal/compiler/resolve.go
  internal/config/override.go
  internal/endtoend/testdata/alias/mysql/go/models.go
  internal/endtoend/testdata/alias/mysql/go/query.sql.go
  internal/endtoend/testdata/codegen_json/gen/codegen.json
  internal/endtoend/testdata/comparisons/mysql/go/models.go
  internal/endtoend/testdata/count_star/mysql/go/models.go
  internal/endtoend/testdata/ddl_alter_table_drop_constraint/mysql/go/models.go
  internal/endtoend/testdata/delete_inner_join/mysql/go/models.go
  internal/endtoend/testdata/delete_join/mysql/db/models.go
  internal/endtoend/testdata/delete_join/mysql/db/query.sql.go
  internal/endtoend/testdata/join_alias/mysql/go/models.go
  internal/endtoend/testdata/join_alias/mysql/go/query.sql.go
  internal/endtoend/testdata/join_right/mysql/go/models.go
  internal/endtoend/testdata/join_right/mysql/go/query.sql.go
  internal/endtoend/testdata/join_table_name/mysql/go/models.go
  internal/endtoend/testdata/join_table_name/mysql/go/query.sql.go
  internal/endtoend/testdata/join_two_tables/mysql/go/models.go
  internal/endtoend/testdata/join_where_clause/mysql/go/models.go
  internal/endtoend/testdata/join_where_clause/mysql/go/query.sql.go
  internal/endtoend/testdata/mix_param_types/mysql/go/models.go
  internal/endtoend/testdata/mix_param_types/mysql/go/test.sql.go
  internal/endtoend/testdata/overrides_unsigned/mysql/go/db.go
  internal/endtoend/testdata/overrides_unsigned/mysql/go/models.go
  internal/endtoend/testdata/overrides_unsigned/mysql/go/query.sql.go
  internal/endtoend/testdata/overrides_unsigned/mysql/query.sql
  internal/endtoend/testdata/overrides_unsigned/mysql/sqlc.json
  internal/endtoend/testdata/prepared_queries/mysql/go/models.go
  internal/endtoend/testdata/prepared_queries/mysql/go/query.sql.go
  internal/endtoend/testdata/process_plugin_disabled/gen/codegen.json
  internal/endtoend/testdata/process_plugin_sqlc_gen_json/gen/codegen.json
  internal/endtoend/testdata/schema_scoped_create/mysql/go/models.go
  internal/endtoend/testdata/schema_scoped_delete/mysql/go/models.go
  internal/endtoend/testdata/schema_scoped_delete/mysql/go/query.sql.go
  internal/endtoend/testdata/schema_scoped_filter/mysql/go/models.go
  internal/endtoend/testdata/schema_scoped_filter/mysql/go/query.sql.go
  internal/endtoend/testdata/schema_scoped_list/mysql/go/models.go
  internal/endtoend/testdata/schema_scoped_list/mysql/go/query.sql.go
  internal/endtoend/testdata/schema_scoped_update/mysql/go/models.go
  internal/endtoend/testdata/schema_scoped_update/mysql/go/query.sql.go
  internal/endtoend/testdata/truncate/mysql/go/models.go
  internal/endtoend/testdata/update_join/mysql/db/models.go
  internal/endtoend/testdata/update_join/mysql/db/query.sql.go
  internal/engine/dolphin/convert.go
  internal/engine/dolphin/utils.go
  internal/plugin/codegen.pb.go
  internal/plugin/codegen_vtproto.pb.go
  internal/sql/ast/column_def.go
  internal/sql/catalog/table.go
  protos/plugin/codegen.proto
Labels: accepted

#1915 fix: check column references in ORDER BY (#1411)
  internal/compiler/expand.go
  internal/compiler/output_columns.go
  internal/compiler/parse.go
  internal/compiler/query_catalog.go
  internal/config/config.go
  internal/config/v_one.go
  internal/config/v_two.go
  internal/endtoend/testdata/order_by_non_existing_column/mysql/query.sql
  internal/endtoend/testdata/order_by_non_existing_column/mysql/sqlc.yaml
  internal/endtoend/testdata/order_by_non_existing_column/mysql/stderr.txt
  internal/endtoend/testdata/order_by_non_existing_column/postgresql/query.sql
  internal/endtoend/testdata/order_by_non_existing_column/postgresql/sqlc.yaml
  internal/endtoend/testdata/order_by_non_existing_column/postgresql/stderr.txt
  internal/endtoend/testdata/order_by_non_existing_column/sqlite/query.sql
  internal/endtoend/testdata/order_by_non_existing_column/sqlite/sqlc.yaml
  internal/endtoend/testdata/order_by_non_existing_column/sqlite/stderr.txt
Labels: accepted

#2121 Support JSON tags for nullable enum structs
  examples/batch/postgresql/models.go
  examples/ondeck/mysql/models.go
  examples/ondeck/postgresql/models.go
  internal/codegen/golang/enum.go
  internal/codegen/golang/field.go
  internal/codegen/golang/result.go
  internal/codegen/golang/templates/template.tmpl
  internal/endtoend/testdata/json_tags_null_enum/camel_case/postgresql/stdlib/go/db.go
  internal/endtoend/testdata/json_tags_null_enum/camel_case/postgresql/stdlib/go/models.go
  internal/endtoend/testdata/json_tags_null_enum/camel_case/postgresql/stdlib/go/query.sql.go
  internal/endtoend/testdata/json_tags_null_enum/camel_case/postgresql/stdlib/query.sql
  internal/endtoend/testdata/json_tags_null_enum/camel_case/postgresql/stdlib/sqlc.json
  internal/endtoend/testdata/json_tags_null_enum/none/postgresql/stdlib/go/db.go
  internal/endtoend/testdata/json_tags_null_enum/none/postgresql/stdlib/go/models.go
  internal/endtoend/testdata/json_tags_null_enum/none/postgresql/stdlib/go/query.sql.go
  internal/endtoend/testdata/json_tags_null_enum/none/postgresql/stdlib/query.sql
  internal/endtoend/testdata/json_tags_null_enum/none/postgresql/stdlib/sqlc.json
  internal/endtoend/testdata/json_tags_null_enum/pascal_case/postgresql/stdlib/go/db.go
  internal/endtoend/testdata/json_tags_null_enum/pascal_case/postgresql/stdlib/go/models.go
  internal/endtoend/testdata/json_tags_null_enum/pascal_case/postgresql/stdlib/go/query.sql.go
  internal/endtoend/testdata/json_tags_null_enum/pascal_case/postgresql/stdlib/query.sql
  internal/endtoend/testdata/json_tags_null_enum/pascal_case/postgresql/stdlib/sqlc.json
  internal/endtoend/testdata/json_tags_null_enum/snake_case/postgresql/stdlib/go/db.go
  internal/endtoend/testdata/json_tags_null_enum/snake_case/postgresql/stdlib/go/models.go
  internal/endtoend/testdata/json_tags_null_enum/snake_case/postgresql/stdlib/go/query.sql.go
  internal/endtoend/testdata/json_tags_null_enum/snake_case/postgresql/stdlib/query.sql
  internal/endtoend/testdata/json_tags_null_enum/snake_case/postgresql/stdlib/sqlc.json
  internal/endtoend/testdata/json_tags_null_enum/v2_config/postgresql/stdlib/go/db.go
  internal/endtoend/testdata/json_tags_null_enum/v2_config/postgresql/stdlib/go/models.go
  internal/endtoend/testdata/json_tags_null_enum/v2_config/postgresql/stdlib/go/query.sql.go
  internal/endtoend/testdata/json_tags_null_enum/v2_config/postgresql/stdlib/query.sql
  internal/endtoend/testdata/json_tags_null_enum/v2_config/postgresql/stdlib/sqlc.json
Labels: accepted

#2342 Update changelog.md
  docs/reference/changelog.md
Labels: documentation
