Repository sqlc-dev/sqlc, pull requests merged in 2025-04, with the labels that each got.

#3913 fix(pgx): Do not wrap nil error
  internal/codegen/golang/templates/pgx/queryCode.tmpl
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/db/query.sql.go
Labels: :wrench: golang, size:S

#3925 [typo] locahost → localhost
  docs/howto/managed-databases.md
Labels: size:XS, lgtm

#3919 fix(migrations): case-sensitive migration rollback detection
  internal/migrations/migrations.go
Labels: size:XS

#3927 build(deps): Upgrade github.com/wasilibs/go-pgquery
  go.mod
  go.sum
Labels: :wrench: golang, size:XS

#3930 Add changelog for 1.29.0
  docs/reference/changelog.md
Labels: size:M
