Repository sqlc-dev/sqlc, pull requests merged in 2025-03, with the labels that each got.

#3854 update csharp support to stable
  docs/reference/language-support.rst
Labels: size:XS

#3887 build: Upgrade to wazero@v1.9.0
  devenv.lock
  devenv.nix
  go.mod
  go.sum
  internal/codegen/golang/postgresql_type.go
  internal/engine/postgresql/convert.go
  internal/engine/postgresql/parse.go
  internal/engine/postgresql/parse_default.go
  internal/engine/postgresql/parser/parser_default.go
  internal/engine/postgresql/utils.go
Labels: :wrench: golang, size:S

#3892 build: Upgrade to Go 1.24.1
  .github/workflows/ci-kotlin.yml
  .github/workflows/ci-python.yml
  .github/workflows/ci-typescript.yml
  .github/workflows/ci.yml
Labels: :wrench: golang, size:XS

#3894 build(deps): bump golang.org/x/net from 0.33.0 to 0.37.0
  go.mod
  go.sum
Labels: :wrench: golang, size:S

#3876 feat(codegen/golang): add an option to wrap query errors that includes query name
  internal/codegen/golang/gen.go
  internal/codegen/golang/imports.go
  internal/codegen/golang/opts/options.go
  internal/codegen/golang/templates/pgx/queryCode.tmpl
  internal/codegen/golang/templates/stdlib/queryCode.tmpl
  internal/endtoend/testdata/wrap_errors/mysql/db/db.go
  internal/endtoend/testdata/wrap_errors/mysql/db/models.go
  internal/endtoend/testdata/wrap_errors/mysql/db/query.sql.go
  internal/endtoend/testdata/wrap_errors/mysql/query.sql
  internal/endtoend/testdata/wrap_errors/mysql/schema.sql
  internal/endtoend/testdata/wrap_errors/mysql/sqlc.yaml
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/db/db.go
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/db/models.go
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/db/query.sql.go
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/query.sql
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/schema.sql
  internal/endtoend/testdata/wrap_errors/postgresql/pgx/sqlc.yaml
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/db/db.go
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/db/models.go
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/db/query.sql.go
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/query.sql
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/schema.sql
  internal/endtoend/testdata/wrap_errors/postgresql/stdlib/sqlc.yaml
  internal/endtoend/testdata/wrap_errors/sqlite/db/db.go
  internal/endtoend/testdata/wrap_errors/sqlite/db/models.go
  internal/endtoend/testdata/wrap_errors/sqlite/db/query.sql.go
  internal/endtoend/testdata/wrap_errors/sqlite/query.sql
  internal/endtoend/testdata/wrap_errors/sqlite/schema.sql
  internal/endtoend/testdata/wrap_errors/sqlite/sqlc.yaml
Labels: :wrench: golang, size:XL, lgtm
