Repository sqlc-dev/sqlc, pull requests merged in 2025-08, with the labels that each got.

#4036 docs: fix parameter syntax inconsistency for MySQL and SQLite
  docs/howto/delete.md
  docs/howto/insert.md
  docs/howto/select.md
  docs/howto/update.md
Labels: size:M

#3711 fix: range subselect alias pointer dereference
  internal/compiler/output_columns.go
  internal/endtoend/testdata/select_subquery_no_alias/mysql/go/db.go
  internal/endtoend/testdata/select_subquery_no_alias/mysql/go/models.go
  internal/endtoend/testdata/select_subquery_no_alias/mysql/go/query.sql.go
  internal/endtoend/testdata/select_subquery_no_alias/mysql/query.sql
  internal/endtoend/testdata/select_subquery_no_alias/mysql/schema.sql
  internal/endtoend/testdata/select_subquery_no_alias/mysql/sqlc.yaml
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/go/db.go
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/go/models.go
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/go/query.sql.go
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/query.sql
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/schema.sql
  internal/endtoend/testdata/select_subquery_no_alias/postgres/stdlib/sqlc.yaml
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/go/db.go
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/go/models.go
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/go/query.sql.go
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/query.sql
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/schema.sql
  internal/endtoend/testdata/select_subquery_no_alias/sqlite/sqlc.yaml
Labels: size:L, lgtm

#4057 chore(engine/dolphin): remove references to deprecated `pcast.ChangeStmt`
  internal/engine/dolphin/convert.go
Labels: :wrench: golang, size:XS

#4061 docs: try a different admonition format
  docs/howto/overrides.md
Labels: size:XS

#4045 bugfix: Normalize identifier usage for table names
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/go/db.go
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/go/models.go
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/go/query.sql.go
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/query.sql
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/schema.sql
  internal/endtoend/testdata/ddl_alter_table_case_sensitivity/sqlite/sqlc.json
  internal/endtoend/testdata/ddl_drop_table/sqlite/schema.sql
  internal/endtoend/testdata/quoted_names_complex/sqlite/go/db.go
  internal/endtoend/testdata/quoted_names_complex/sqlite/go/models.go
  internal/endtoend/testdata/quoted_names_complex/sqlite/go/query.sql.go
  internal/endtoend/testdata/quoted_names_complex/sqlite/query.sql
  internal/endtoend/testdata/quoted_names_complex/sqlite/schema.sql
  internal/endtoend/testdata/quoted_names_complex/sqlite/sqlc.json
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/go/db.go
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/go/models.go
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/go/query.sql.go
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/query.sql
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/schema.sql
  internal/endtoend/testdata/table_name_case_sensitivity/sqlite/sqlc.json
  internal/engine/sqlite/convert.go
Labels: :wrench: golang, size:XL, lgtm

#4067 docs: add multi-worded table example for renaming
  docs/howto/rename.md
Labels: size:S, lgtm

#4074 build(deps): Upgrade to Go 1.25
  .github/workflows/ci.yml
Labels: :wrench: golang, size:XS
