Repository sqlc-dev/sqlc, pull requests merged in 2025-01, with the labels that each got.

#3767 docs: Fix sqlite package import
  docs/tutorials/getting-started-sqlite.md
Labels: size:XS

#3795 build: Upgrade to Go 1.23.5
  .github/workflows/ci.yml
Labels: size:S

#3797 docs: Add changelog for 1.28.0
  docs/reference/changelog.md
Labels: size:M

#3813 new community generator plugin for PHP
  docs/reference/language-support.rst
Labels: size:S, lgtm
