Repository sqlc-dev/sqlc, pull requests merged in 2025-02, with the labels that each got.

#3831 build: Use govulncheck action
  .github/workflows/ci.yml
Labels: :wrench: golang, size:XS

#3828 examples: Add missing Close calls
  examples/authors/sqlite/db_test.go
  examples/booktest/sqlite/db_test.go
  examples/ondeck/sqlite/db_test.go
  internal/sqltest/sqlite.go
Labels: size:XS

#3829 docs: Fix PostGIS function name
  docs/reference/datatypes.md
Labels: size:XS

#3824 docs: Add Zig plugin
  docs/reference/language-support.rst
Labels: size:XS, lgtm

#3827 Add support for json format from process plugins
  .github/workflows/ci.yml
  Makefile
  docs/guides/plugins.md
  docs/reference/config.md
  internal/cmd/generate.go
  internal/config/config.go
  internal/endtoend/testdata/process_plugin_format_json/exec.json
  internal/endtoend/testdata/process_plugin_format_json/gen/hello.txt
  internal/endtoend/testdata/process_plugin_format_json/query.sql
  internal/endtoend/testdata/process_plugin_format_json/schema.sql
  internal/endtoend/testdata/process_plugin_format_json/sqlc.json
  internal/ext/process/gen.go
  scripts/test-json-process-plugin/main.go
Labels: size:L, lgtm

#3819 docs: add link to java plugin
  docs/reference/language-support.rst
Labels: size:S

#3811 Update postgresql_type.go: accept "timestamp" as a case
  internal/codegen/golang/postgresql_type.go
Labels: :wrench: golang, size:XS, lgtm

#3843 docs: update supported engines for sqlc-gen-java
  docs/reference/language-support.rst
Labels: size:XS

#3845 Add sqlite beta support for zig plugin
  docs/reference/language-support.rst
Labels: size:XS
